### ISSUE TITLE
Adding Javaprinter

### ISSUE THREAD

**Issue by pxlfrk** [misery/ordersprinter#5]
Hi André,

found your awesome dockerfile - thanks for all the work you've done here so far.
Did you manage to setup Ordersprinter on Docker with the JavaPrinter, too? I'm currently struggling to set this up in addition.

**Comment by misery** [comment]
Hi!

I do not use the javaprinter. But that shouldn't be a problem to move that to a separate container. What is your problem? Do you have Linux or Windows as your host? Do you have some stuff already?

**Comment by pxlfrk** [comment]
Hi,

Thanks for your reply. In the meantime, I found a working solution that fits my need. In case any other users stumble upon this issue:

In our environment the OrderSprinter instance is running as as compose stack in portainer (using this template file, thank you!) and is publicly accessible in the internet through a proxy host in the nginx proxy manager.

In the Store there is a local windows Client on which the OrderSprinter PrintServer for Windows is running locally. This PrintServer is connected via http and prints out the receipts issued by the server instance.

It is important to notice that the PrintServee isn't capable of using HTTPS protocol, so in the proxy configuration you have to disable the force-ssl setting.

We're requested a SSL certificate in addition, so the mobile users can connect via HTTPS. We also set up an access control list via basic Auth in NPM to secure the connection to the OrderSprinter Instance as good as possible.

The information, that the PrintServer isn't supporting SSL at the moment is quite hidden in the documentation.

So, as this isn't an issue of this template, feel free to close this issue. Thanks!
